volumes:
  mssqlvolume:

services:
  web_api:
    image: web_api
    container_name: web_api_application
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: ms_sql_server
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=myDBpas12.WORD
    volumes:
      - mssqlvolume:/var/opt/mssql

